### ISSUE TITLE
how to use generate_route.rs / city_strides_route_generator?

### ISSUE THREAD

**Issue by monperrus** [codereport/city-strides-hacking#11]
Thanks for the great repo.

I am able to download all the nodes of my city and to plot them.

Next, I want to compute the route, but I don't succeed:

```
± ./city_strides_route_generator 
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

I am not making progress by reading the `main` of `generate_route`.

Any help would be much appreciated!

Thanks!

**Comment by codereport** [comment]
Do you have the `parameters.yaml` setup?

**Comment by monperrus** [comment]
yes, I do. Thanks.

**Comment by monperrus** [comment]
the trick was to download the missing data on overpass, see https://github.com/codereport/city-strides-hacking/pull/12

thanks!
